# config/packages/knp_paginator.yaml
knp_paginator:
    page_range: 5
    default_options:
        page_name: page
        sort_field_name: sort
        sort_direction_name: direction
        filter_field_name: filterField
        filter_value_name: filterValue
    template: null  # Utilisation du template par défaut
    # template: '@KnpPaginator/Pagination/bootstrap_v4.html.twig'
