parameters:
    photos_directory: '%kernel.project_dir%/public/uploads/photosevents'

    uploads_directory: '%kernel.project_dir%/public/uploads/cours'

    twilio.sid: "%env(TWILIO_SID)%"
    twilio.auth_token: "%env(TWILIO_AUTH_TOKEN)%"
    twilio.phone_number: "%env(TWILIO_PHONE_NUMBER)%"
    
    magasin_directory: '%kernel.project_dir%/public/uploads/magasin'
    produits_directory: '%kernel.project_dir%/public/uploads/produits'
    photos_directory: '%kernel.project_dir%/public/uploads/photos'
    photos_events_directory: '%kernel.project_dir%/public/uploads/photosevents'


services:
<<<<<<< HEAD
    # default configuration for services in *this* file
    

    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
  
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
    
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
=======
  _defaults:
    autowire: true
    autoconfigure: true

  # Defines the App services
  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'
>>>>>>> 67ede58c13395a5f2206417896f7661b70eb0dd6

  App\Service\TwilioService:
    arguments:
      $sid: "%twilio.sid%"
      $token: "%twilio.auth_token%"
      $twilioNumber: "%twilio.phone_number%"