parameters:
  twilio.sid: "%env(TWILIO_SID)%"
  twilio.auth_token: "%env(TWILIO_AUTH_TOKEN)%"
  twilio.phone_number: "%env(TWILIO_PHONE_NUMBER)%"
  
  magasin_directory: '%kernel.project_dir%/public/uploads/magasin'
  produits_directory: '%kernel.project_dir%/public/uploads/produits'
  photos_directory: '%kernel.project_dir%/public/uploads/photos'
  photos_events_directory: '%kernel.project_dir%/public/uploads/photosevents'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  # Defines the App services
  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  App\Service\TwilioService:
    arguments:
      $sid: "%twilio.sid%"
      $token: "%twilio.auth_token%"
      $twilioNumber: "%twilio.phone_number%"